name: Postgres tests

on: push

jobs:
  pgtap:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2

      - name: Install postgres dev
        run: sudo apt-get install -y --no-install-recommends postgresql-server-dev-all

      - name: Build && Install extension
        run: make && sudo make install
        env:
          PGPASSWORD: postgres

      - name: Install pg_prove
        run: sudo cpan TAP::Parser::SourceHandler::pgTAP
        env:
          SHELL: /bin/bash

      - name: Checkout pgtap
        uses: actions/checkout@v2
        with:
          repository: theory/pgtap
          path: pgtap
          tag: v1.1.0

      - name: Install pgtap
        working-directory: pgtap
        run: make && psql --host localhost --username postgres --dbname postgres --file sql/pgtap.sql
        env:
          PGPASSWORD: postgres

      - name: Run pgtap tests
        run: pg_prove --host localhost --dbname postgres --username postgres test/*.sql
        env:
          PGPASSWORD: postgres